version: "3.5"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

  
services:


  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "1.1"
          memory: "300MB"


  api01:  &api
    build:
      context: ./api
      dockerfile: dockerfile
    hostname: api01
    networks:
      - default
    depends_on:
      - db
    environment:
      - DB_USER=admin
      - DB_NAME=db
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
      - SERVER_PORT=3000
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "110MB"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 10; done; ./main'
    ports:
      - 3001:3000

  api02:
    <<: *api
    ports:
      - 3002:3000
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "110MB"

  nginx:
    networks:
      - default
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"